version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cragmaster-backend
    restart: unless-stopped

    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./db:/app/db

    ports:
      - "5757:5757"

  frontend:
    build: ./frontend
    container_name: cragmaster-frontend
    restart: unless-stopped

    volumes:
      - ./static:/app/static

    ports:
      - "5173:5173"

    depends_on:
      - backend
