name: cragmaster

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip

  # OCR / PDF stack
  - tesseract
  - poppler

  - pip:
      - attrs
      - bcrypt
      - beautifulsoup4
      - blinker
      - cffi
      - charset-normalizer
      - click
      - cryptography
      - flask
      - flask-cors
      - flask-jwt-extended
      - flask-limiter
      - fuzzysearch
      - itsdangerous
      - jinja2
      - markupsafe
      - pdf2image
      - pdfminer-six
      - pdfplumber
      - pillow
      - pycparser
      - pyjwt
      - pypdfium2
      - pytesseract
      - gunicorn
      - werkzeug
