var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,b){a instanceof String&&(a=String(a));for(var c=a.length,d=0;d<c;d++){var f=a[d];if(e.call(b,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){if(a==Array.prototype||a==Object.prototype)return a;a[e]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<a.length;++e){var b=a[e];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,e){var b=$jscomp.propertyToPolyfillSymbol[e];if(null==b)return a[e];b=a[b];return void 0!==b?b:a[e]};
$jscomp.polyfill=function(a,e,b,c){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,e,b,c):$jscomp.polyfillUnisolated(a,e,b,c))};$jscomp.polyfillUnisolated=function(a,e,b,c){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in b||(b[d]={});b=b[d]}a=a[a.length-1];c=b[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(a,e,b,c){var d=a.split(".");a=1===d.length;c=d[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];g in c||(c[g]={});c=c[g]}d=d[d.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?c[d]:null;e=e(b);null!=e&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:e}):e!==b&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=$jscomp.propertyToPolyfillSymbol[d],
$jscomp.defineProperty(c,d,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
var dud=function(a){a(function(){var e=a.support;a:{var b=document.createElement("bootstrap");var c={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},d;for(d in c)if(void 0!==b.style[d]){b=c[d];break a}b=void 0}e.transition=b&&{end:b}})}(window.jQuery);
dud=function(a){var e=function(b,c){this.$element=a(b);this.options=a.extend({},a.fn.button.defaults,c)};e.prototype.setState=function(a){var b=this.$element,d=b.data(),f=b.is("input")?"val":"html";a+="Text";d.resetText||b.data("resetText",b[f]());b[f](d[a]||this.options[a]);setTimeout(function(){"loadingText"==a?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)};e.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};a.fn.button=function(b){return this.each(function(){var c=a(this),d=c.data("button"),f="object"==typeof b&&b;d||c.data("button",d=new e(this,f));"toggle"==b?d.toggle():b&&d.setState(b)})};a.fn.button.defaults={loadingText:"loading..."};a.fn.button.Constructor=e;a(function(){a("body").on("click.button.data-api","[data-toggle^=button]",function(b){b=a(b.target);b.hasClass("btn")||(b=b.closest(".btn"));b.button("toggle")})})}(window.jQuery);
dud=function(a){function e(){a("[data-toggle=dropdown]").each(function(){var c=b(a(this));c.removeClass("open");c=c.find(".dropdown-menu");c.css("max-width","");c.css("right","")})}function b(b){var c=b.attr("data-target");c||(c=(c=b.attr("href"))&&/#/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));(c=c&&a(c))&&c.length||(c=b.parent());return c}var c=function(b){var c=a(b).on("click.dropdown.data-api",this.toggle);a("html").on("click.dropdown.data-api",function(){c.parent().removeClass("open")})};c.prototype=
{constructor:c,toggle:function(c){c=a(this);if(!c.is(".disabled, :disabled")){var d=b(c);var f=d.hasClass("open");e();f||(d.toggleClass("open"),d=d.find(".dropdown-menu"),d.hasClass("pull-right")&&(d.css("max-width",window.innerWidth-8),f=d.offset().left,0>f&&d.css("right",f-4+"px")));c.focus();return!1}},keydown:function(c){if(/(38|40|27)/.test(c.keyCode)){var d=a(this);c.preventDefault();c.stopPropagation();if(!d.is(".disabled, :disabled")){var e=b(d);var f=e.hasClass("open");if(!f||f&&27==c.keyCode)return 27==
c.which&&e.find("[data-toggle=dropdown]").focus(),d.click();d=a("[role=menu] li:not(.divider):visible a",e);d.length&&(e=d.index(d.filter(":focus")),38==c.keyCode&&0<e&&e--,40==c.keyCode&&e<d.length-1&&e++,~e||(e=0),d.eq(e).focus())}}}};var d=a.fn.dropdown;a.fn.dropdown=function(b){return this.each(function(){var d=a(this),e=d.data("dropdown");e||d.data("dropdown",e=new c(this));"string"==typeof b&&e[b].call(d)})};a.fn.dropdown.Constructor=c;a.fn.dropdown.noConflict=function(){a.fn.dropdown=d;return this};
a(document).on("click.dropdown.data-api",e).on("click.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.dropdown-menu",function(a){a.stopPropagation()}).on("click.dropdown.data-api","[data-toggle=dropdown]",c.prototype.toggle).on("keydown.dropdown.data-api","[data-toggle=dropdown], [role=menu]",c.prototype.keydown)}(window.jQuery);
dud=function(a){var e=function(b,c){this.options=c;this.$element=a(b).delegate('[data-dismiss="modal"]',"click.dismiss.modal",a.proxy(this.hide,this));this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};e.prototype={constructor:e,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var b=this,c=a.Event("show");this.$element.trigger(c);this.isShown||c.isDefaultPrevented()||(a("body").addClass("modal-open"),this.isShown=!0,this.escape(),this.backdrop(function(){var c=
a.support.transition&&b.$element.hasClass("fade");b.$element.parent().length||b.$element.appendTo(document.body);b.$element.show();b.$element.addClass("in").attr("aria-hidden",!1).focus();b.enforceFocus();c?b.$element.one(a.support.transition.end,function(){b.$element.trigger("shown")}):b.$element.trigger("shown")}))},hide:function(b){b&&b.preventDefault();b=a.Event("hide");this.$element.trigger(b);this.isShown&&!b.isDefaultPrevented()&&(this.isShown=!1,a("body").removeClass("modal-open"),this.escape(),
a(document).off("focusin.modal"),this.$element.removeClass("in").attr("aria-hidden",!0),a.support.transition&&this.$element.hasClass("fade")?this.hideWithTransition():this.hideModal())},enforceFocus:function(){var b=this;a(document).on("focusin.modal",function(a){b.$element[0]===a.target||b.$element.has(a.target).length||b.$element.focus()})},escape:function(){var a=this;if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.modal",function(b){27==b.which&&a.hide()});else this.isShown||
this.$element.off("keyup.dismiss.modal")},hideWithTransition:function(){var b=this,c=setTimeout(function(){b.$element.off(a.support.transition.end);b.hideModal()},500);this.$element.one(a.support.transition.end,function(){clearTimeout(c);b.hideModal()})},hideModal:function(a){this.$element.hide().trigger("hidden");this.backdrop()},removeBackdrop:function(){this.$backdrop.remove();this.$backdrop=null},backdrop:function(b){var c=this.$element.hasClass("fade")?"fade":"",d=0;if(this.isShown&&this.options.backdrop){var e=
a.support.transition&&c;this.$backdrop=a('<div class="modal-backdrop '+c+'" />').appendTo(document.body);"static"!=this.options.backdrop&&this.$backdrop.click(a.proxy(this.hide,this));e&&(d=this.$backdrop[0].offsetWidth);this.$backdrop.addClass("in");e?this.$backdrop.one(a.support.transition.end,b):b()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),a.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(a.support.transition.end,a.proxy(this.removeBackdrop,this)):
this.removeBackdrop()):b&&b();return d}};a.fn.modal=function(b){return this.each(function(){var c=a(this),d=c.data("modal"),f=a.extend({},a.fn.modal.defaults,c.data(),"object"==typeof b&&b);d||c.data("modal",d=new e(this,f));if("string"==typeof b)d[b]();else f.show&&d.show()})};a.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};a.fn.modal.Constructor=e;a(function(){a("body").on("click.modal.data-api",'[data-toggle="modal"]',function(b){var c=a(this),d=c.attr("href"),e=a(c.attr("data-target")||
d&&d.replace(/.*(?=#[^\s]+$)/,""));d=e.data("modal")?"toggle":a.extend({remote:!/#/.test(d)&&d},e.data(),c.data());b.preventDefault();e.modal(d).one("hide",function(){c.focus()})})})}(window.jQuery);
